kind: pipeline
type: docker
name: test

steps:
  - name: fetch
    image: alpine/git
    commands:
      - git fetch --tags

  - name: Test Python
    depends_on:
      - fetch
    image: python:3.13
    commands:
      - curl https://qlty.sh | sh
      - pip install -e .[test]
      - ruff check .
      - mypy .
      - coverage run -m unittest
      - coverage report -m
      - coverage lcov -o .coverage.lcov
      - ~/.qlty/bin/qlty coverage publish .coverage.lcov --override-commit-sha "$DRONE_COMMIT_SHA" --override-branch "$DRONE_BRANCH" --override-build-id "$DRONE_BUILD_NUMBER"
    environment:
      QLTY_COVERAGE_TOKEN: qltcp_JTdhvfxYWFWQ7gmW

  - name: Test Python Packaging
    image: python:3.13
    commands:
      - pip install build twine
      - python -m build
      - twine check --strict dist/*

  - name: Upload Python
    depends_on:
      - Test Python
      - Test Python Packaging
    environment:
      TWINE_USERNAME:
        from_secret: twine_username
      TWINE_PASSWORD:
        from_secret: twine_password
    image: python:3.13
    commands:
      - pip install build twine
      - python -m build
      - twine upload dist/*
    when:
      event:
        - tag
